mydb:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=demo
    - MYSQL_USER=demo_user
    - MYSQL_PASSWORD=demo_pass
  ports:
    - 3306:3306
  volumes:
    - //d/workspace_dc/tmp:/var/lib/mysql
  container_name: mydb
mywas:
  image: dockerized_java_webapp:latest
  ports:
    - 9090:8080
  links:
    - mydb:mysql
  container_name: mywas